### ISSUE TITLE
README needs more info

### ISSUE THREAD

**Issue by Botster** [kewlfft/opennic-up#1]
First off, thank you very much for this utility. It works great and is very handy.

The README could use a bit more information though.

Only upon executing the script was I informed that I also needed 'fping' and 'drill'. (I finally found drill in the 'ldns' package.)

After installing fping, the script still said it couldn't find it. It was not in my user path, because it was installed to /usr/sbin/ .

1. Apparently the script needs to be run as root?

2. The README informs where opennic-up and opennic-up.conf can reside, but does not say where opennic-up.timer and opennic-up.service should be placed.

And just FYI, there is a typo: "For a full integration of the automated update process with you system and with systemd..." Should be, "your system".

**Comment by kewlfft** [comment]
Thanks for the feedback, it does not need to be run as root, what makes you say so?
Otherwise I am going to take your comments into account.

**Comment by Botster** [comment]
I questioned whether the script needs to be run as root due to:
1) its reliance on fping which is installed to /usr/sbin, and that making it not in a regular user's path, and
2) when I execute /usr/sbin/fping 127.0.0.1 or /usr/sbin/fping 191.168.0.1, I get:
/usr/sbin/fping: can't create raw socket (must run as root?) : Operation not permitted

**Comment by kewlfft** [comment]
I have `fping` 4.0 in `/usr/bin` and it does not require root access. Anyway this is more about fping than about my tool, we could use ping instead but it would be much slower and less reliable.

**Comment by Botster** [comment]
I looked at the fping documentation on their site and github and saw no mention of needing elevated privileges. The version I have is 3.5, but I don't think it's a version issue. I think it is a distribution system security configuration issue.

That being said, I would not be in favor of reverting to 'ping' for the very reasons you stated.

I'm going to close this issue.
