### ISSUE TITLE
resolvconf is a read-only variable

### ISSUE THREAD

**Issue by tmtvl** [kewlfft/opennic-up#12]
On line 3 you set:

```shell
readonly resolvconf="/etc/resolv.conf"
```

And then on line 65 you do:

```shell
f)  resolvconf=$OPTARG
```

That doesn't work and the script warns me that it doesn't work and it writes to `/etc/resolv.conf` instead of `/opt/resolv.conf`, which I specified.

**Comment by gholam-deblan** [comment]
Good point I've removed the readonly, can you check?

**Comment by kewlfft** [comment]
Good point I've removed the read-only, can you check?

**Comment by tmtvl** [comment]
Seems to work fine, just cut a new release and it can be updated on the AUR.
