### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by SJablonska** [kewlfft/opennic-up#5]
Hi certainly, then I am not using ipv6 servers myself and haven't implemented it

_Originally posted by @kewlfft in https://github.com/kewlfft/opennic-up/issues/4#issuecomment-555977204_

What would you need to implement it?

**Comment by kewlfft** [comment]
Time and interest, therefore I will not implement it.

**Comment by SJablonska** [comment]
Clear :-)

**Comment by tuxayo** [comment]
Can the issue be implemented with a statement that it's open for external contributions?
